language: csharp
solution: CsvLINQPadDriver.sln
before_install:
  - sed -i 's/\(<Reference Include="PresentationCore" \/>\)/<!-- \1 -->/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
  - sed -i 's/\(<Reference Include="PresentationFramework" \/>\)/<!-- \1 -->/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
  - sed -i 's/\(<PostBuildEvent>DevDeploy.bat<\/PostBuildEvent>\)/<!-- \1 -->/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
  - sed -i 's/<Compile Include="ConnectionDialog.xaml.cs">/<Compile Include="ConnectionDialog-NoWPF.cs">/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj 
  - sed -i 's/<Page/<Resource/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
  - sed -i 's/<\/Page/<\/Resource/' ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
  - cat ./Src/CsvLINQPadDriver/CsvLINQPadDriver.csproj
install:
  - nuget restore CsvLINQPadDriver.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CsvLINQPadDriver.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Release/Tests/CsvLINQPadDriverTest.dll
  